export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const PARTICULAR_PRODUCT_REQUEST = "PARTICULAR_PRODUCT_REQUEST";
export const PARTICULAR_PRODUCT_SUCCESS = "PARTICULAR_PRODUCT_SUCCESS";
export const PARTICULAR_PRODUCT_FAIL = "PARTICULAR_PRODUCT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";